import * as HeadlessUI from './index'

/**
 * Looks a bit of a silly test, however this ensures that we don't accidentally expose something to
 * the outside world that we didn't want!
 */
it('should expose the correct components', () => {
  expect(Object.keys(HeadlessUI)).toEqual([
    'Description',
    'Label',
    'Portal',
    'ComboboxButton',
    'ComboboxInput',
    'ComboboxLabel',
    'ComboboxOptions',
    'ComboboxOption',
    'Combobox',
    'DialogPanel',
    'DialogTitle',
    'DialogDescription',
    'Dialog',
    'DisclosureButton',
    'DisclosurePanel',
    'Disclosure',
    'FocusTrap',
    'ListboxButton',
    'ListboxLabel',
    'ListboxOptions',
    'ListboxOption',
    'Listbox',
    'MenuButton',
    'MenuItems',
    'MenuItem',
    'Menu',
    'PopoverButton',
    'PopoverOverlay',
    'PopoverPanel',
    'PopoverGroup',
    'Popover',
    'RadioGroupOption',
    'RadioGroupLabel',
    'RadioGroupDescription',
    'RadioGroup',
    'SwitchGroup',
    'SwitchLabel',
    'SwitchDescription',
    'Switch',
    'TabGroup',
    'TabList',
    'TabPanels',
    'TabPanel',
    'Tab',
    'TransitionChild',
    'Transition',
  ])
})
